version: '3.9'

services:
  web:
    build: .
    container_name: django_gunicorn
    expose:
      - "8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=mainapp.settings
      - DEBUG=False  # Make sure this is False for production!

  nginx:
    image: nginx:latest
    container_name: django_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: