version: '3.9'

services:
  web:
    build: .
    container_name: django_gunicorn
    expose:
      - "8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_URL=${DATABASE_URL}
  nginx:
    image: nginx:latest
    container_name: django_nginx
    ports:
      - "6080:80"    # HTTP exposed externally on port 6080
      - "6443:443"   # HTTPS exposed externally on port 6443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: